[libeufin-bank]
CURRENCY = KUDOS
BASE_URL = http://libeufin-bank:8080/
PWD_AUTH_COMPAT = yes
DEFAULT_DEBT_LIMIT = KUDOS:200000
REGISTRATION_BONUS = KUDOS:100
SUGGESTED_WITHDRAWAL_EXCHANGE = http://taler-exchange:8081/
SPA_CAPTCHA_URL = http://libeufin-bank:8080/#/operation/{woid}
WIRE_TYPE = iban

[libeufin-bankdb-postgres]
CONFIG = jdbc:postgresql://postgres:5432/libeufin_bank?user=taler&password=talerpassword

