#!/bin/bash
# Initialize Taler Exchange
set -e

echo "=== Initializing Taler Exchange ==="

# Use provided config or default
CONF_FILE="${TALER_CONFIG:-/etc/taler/taler.conf}"

# If using the copied config from docker-compose
if [ -f /tmp/taler-exchange.conf ]; then
    CONF_FILE=/tmp/taler-exchange.conf
    export TALER_CONFIG=/tmp/taler-exchange.conf
fi

echo "Using config: $CONF_FILE"

# Check if config exists and is readable
if [ ! -f "$CONF_FILE" ]; then
    echo "ERROR: Config file not found: $CONF_FILE"
    exit 1
fi

# Show config content for debugging
echo "Config BASE_URL:"
grep "BASE_URL" "$CONF_FILE" | head -1

# Wait for PostgreSQL
echo "Waiting for PostgreSQL..."
until pg_isready -h postgres -U taler; do
    echo "  PostgreSQL not ready, waiting..."
    sleep 2
done
echo "PostgreSQL is ready"

# Ensure exchange database exists
echo "Checking exchange database..."
if ! PGPASSWORD=talerpassword psql -h postgres -U taler -tc "SELECT 1 FROM pg_database WHERE datname = 'taler_exchange'" | grep -q 1; then
    echo "Creating taler_exchange database..."
    PGPASSWORD=talerpassword psql -h postgres -U taler -c "CREATE DATABASE taler_exchange;"
fi

# Initialize database schema
echo "Initializing exchange database schema..."
taler-exchange-dbinit -c "$CONF_FILE" 2>&1 || {
    echo "DB init may have already been done or failed"
}

# Wait for fakebank
echo "Waiting for fakebank..."
for i in {1..30}; do
    if curl -sf http://fakebank:8082/healthz >/dev/null 2>&1 || \
       curl -sf http://fakebank:8082/accounts >/dev/null 2>&1; then
        echo "Fakebank is ready"
        break
    fi
    echo "  Waiting for fakebank... ($i/30)"
    sleep 2
done

# Generate master key using 'setup' command (not 'generate-key')
# This creates master.priv and outputs the public key
if [ ! -f /var/lib/taler-exchange/master.priv ]; then
    echo "Generating exchange master key with 'taler-exchange-offline setup'..."
    # Run setup and capture the public key output
    SETUP_OUTPUT=$(taler-exchange-offline -c "$CONF_FILE" setup 2>&1) || {
        echo "Setup command output: $SETUP_OUTPUT"
    }
    echo "Setup output: $SETUP_OUTPUT"
    
    # Extract the public key from the output (it's a base32 string)
    MASTER_PUB=$(echo "$SETUP_OUTPUT" | grep -o '[A-Z2-7]\{52\}' | head -1 || echo "")
    
    if [ -n "$MASTER_PUB" ]; then
        echo "Found master public key from setup: $MASTER_PUB"
        # Add to config
        if ! grep -q "MASTER_PUBLIC_KEY" "$CONF_FILE"; then
            echo "" >> "$CONF_FILE"
            echo "# Master public key (auto-generated by setup)" >> "$CONF_FILE"
            echo "MASTER_PUBLIC_KEY = $MASTER_PUB" >> "$CONF_FILE"
            echo "Added MASTER_PUBLIC_KEY to config"
        fi
    else
        echo "WARNING: Could not extract public key from setup output"
    fi
else
    echo "Master key already exists at /var/lib/taler-exchange/master.priv"
    # If master.priv exists but MASTER_PUBLIC_KEY not in config, try to extract it
    if ! grep -q "MASTER_PUBLIC_KEY" "$CONF_FILE"; then
        echo "Extracting public key from existing master.priv..."
        # Try to get the public key using the offline tool
        INFO_OUTPUT=$(taler-exchange-offline -c "$CONF_FILE" info 2>&1 || echo "")
        MASTER_PUB=$(echo "$INFO_OUTPUT" | grep -o '[A-Z2-7]\{52\}' | head -1 || echo "")
        
        if [ -z "$MASTER_PUB" ]; then
            # Try to read from master.priv directly - format is usually base32 encoded key
            MASTER_PUB=$(cat /var/lib/taler-exchange/master.priv 2>/dev/null | grep -o '[A-Z2-7]\{52\}' | head -1 || echo "")
        fi
        
        if [ -n "$MASTER_PUB" ]; then
            echo "Extracted public key: $MASTER_PUB"
            echo "" >> "$CONF_FILE"
            echo "# Master public key (extracted from existing key)" >> "$CONF_FILE"
            echo "MASTER_PUBLIC_KEY = $MASTER_PUB" >> "$CONF_FILE"
        else
            echo "WARNING: Could not extract public key"
        fi
    fi
fi

# Show current key status
echo ""
echo "Exchange key status:"
ls -la /var/lib/taler-exchange/ 2>/dev/null | grep -E "(master|priv|pub)" || echo "(no key files found)"

# Check if MASTER_PUBLIC_KEY is now in config
if grep -q "MASTER_PUBLIC_KEY" "$CONF_FILE"; then
    echo ""
    echo "MASTER_PUBLIC_KEY configured:"
    grep "MASTER_PUBLIC_KEY" "$CONF_FILE" | head -1
else
    echo "WARNING: MASTER_PUBLIC_KEY not found in config!"
fi

# Set up wire fees
echo ""
echo "Setting up wire fees..."
taler-exchange-offline -c "$CONF_FILE" wire-fees 2024 KUDOS 0 0 0 2>&1 || true

# Sign denominations
echo "Signing denomination keys..."
taler-exchange-offline -c "$CONF_FILE" sign 2>&1 || {
    echo "Note: sign may have warnings if no denominations ready"
}

# Start httpd briefly to generate keys
echo ""
echo "Starting exchange httpd to generate denomination keys..."
taler-exchange-httpd -c "$CONF_FILE" &
HTTPD_PID=$!

# Wait for keys endpoint
echo "Waiting for /keys endpoint..."
for i in {1..60}; do
    if curl -sf http://localhost:8081/keys >/dev/null 2>&1; then
        echo "Keys endpoint is ready!"
        break
    fi
    echo "  Waiting for keys... ($i/60)"
    sleep 2
done

# Kill temporary httpd
if kill -0 $HTTPD_PID 2>/dev/null; then
    echo "Stopping temporary httpd..."
    kill $HTTPD_PID
    wait $HTTPD_PID 2>/dev/null || true
fi

echo ""
echo "=== Starting Exchange Services ==="

# Start helper services
taler-exchange-wirewatch -c "$CONF_FILE" &
taler-exchange-closer -c "$CONF_FILE" &
taler-exchange-aggregator -c "$CONF_FILE" &
taler-exchange-transfer -c "$CONF_FILE" &

sleep 2

echo ""
echo "=== Starting Exchange HTTPD ==="
exec taler-exchange-httpd -c "$CONF_FILE" -L INFO
